config/routes.rb
YorkStreetClub::Application.routes.draw do
  
  root "static_pages#home"

  match '/about',       to: 'static_pages#about',       via: 'get'
  match '/schedule',    to: 'static_pages#schedule',    via: 'get'
  match '/rules',       to: 'static_pages#rules',       via: 'get'
  match '/sponsors',    to: 'static_pages#sponsors',    via: 'get'
  match '/service',     to: 'static_pages#service',     via: 'get'
  match '/contact',     to: 'static_pages#contact',     via: 'get'
  match '/membership',  to: 'static_pages#member',      via: 'get'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def schedule
  end

  def about
  end

  def rules
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(page_title)
	base_title = "1311 York Street Club"
	if page_title.empty?
	  base_title
	else 
	  "#{page_title}"
	end
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/_device_specific.html.erb
  <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_footer.html.erb
	<div class="navbar navbar-fixed-bottom" id='footer'>
  	<div class='container'>
  		<div class='row-fluid'>
      	 <div class="span4">
      	 	<%= link_to "1311 York St. Denver, CO, 80206", "http://maps.google.com/?q=1311 York St, Denver, CO, 80206", :target => "_blank" %>
      	 </div>
      	 <div class="span4">303-322-3674</div>
      	 <div class="span4">&copy; 1311 York St. Inc 2013</div>
			</div>
		</div>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" id='changebutton' data-target=".nav-collapse" data-toggle="collapse">
        <i class="icon-chevron-down"></i>
      </a>
      <a class="brand" href="/">1311 York Street Club</a>
      <div class="nav-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Meetings", schedule_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Rules", rules_path %></li>
        </ul>

        <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
 <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>   
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= render 'layouts/device_specific' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
  <%= render 'layouts/header' %>
<p id="bodytop"></p>
  
          <%= bootstrap_flash %>
          <%= yield %>
          <%= debug(params) if Rails.env.development? %>

  <%= render 'layouts/footer' %>

    </div>

  </body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, "About the Club") %>

<h1>About The Club</h1>
<p>The Own LeFevre House is located at 1311 York Street on the border of the Cheeseman Park and Congress Park neighborhoods. Built in 1896, at a cost of $45,000 the Owen LeFevre House would have been in a quaint and beautiful location, not at all like the bustling intersection that 13th and York is today. </br>
Built for Owen LeFevre and his wife Eva French LeFevre, the elegant Owen LeFevre House was built with a wonderful wrap-around porch that runs the full length of the south and east sides of the home. Mr. & Mrs. Owen LeFevre had one child, a daughter named Frederica. Owen LeFevre was a prominent judge in Denver until 1901. Afterwards, he retired from the bench, and returned to private practice in Denver. Judge Owen LeFevre was also a prominent member of the Republican Party in which he was very active. On a personal note, Judge Owen LeFevre was particularly fond of books, and had one of the largest private libraries found in Denver. The Owen LeFevre house was also known for having one of the finest collections of French Art west of the Mississippi. Owen LeFevre passed in 1921, and his widow Eva LeFevre stayed at the Owen LeFevre House for the remainder of her life. Mrs. Eva LeFevre died in 1948. After her passing, several buyers came forward with offers to purchase the Owen LeFevre House, but the heirs of Mrs. LeFevre decided that for philanthropic reasons, the Owen LeFevre House should be sold to York Street #1, a local group of Alcoholics Anonymous, for an amount of $25,000. Many conversions and restorations took place at the Owen LeFevre House at a cost of over $220,000 which came from State Historic Funds. Since then, the Owen LeFevre House has been the center of Alcoholics Anonymous in Denver for over 50 years. </br>
Each time I drive by the Owen LeFevre House, I see people relazing in the large wrap-around porch, and I think about its history. What a wonderful location for an organization that has assisted countless Denver residents in reclaiming their lives over the last several decades. The Owen LeFevre House was entered into the national register of Historic Places in August of 1976.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>

<div class="container-fluid span6 offset3 pull-left" id='contact'>
<!--     		    <%= link_to "http://www.aa.org", :target => "_blank", class: "pull-left" do %>
            <i class="icon-globe"></i>
            <%= t("Official Alcoholics Anonymous Site") %>
            <% end %>
 -->            <br>
		<%= link_to "http://maps.google.com/?q=1311 York St, Denver, CO, 80206", :target => "_blank", class: "pull-left" do %>
            <i class="icon-map-marker"></i>
            <%= t(:Directions) %>
            <% end %>
            <br>
            <%= mail_to "joesusnick@gmail.com", class: "pull-left" do %>
            <i class="icon-envelope"></i>
            <%= t("Email Us") %>
            <% end %>
</div>

app/views/static_pages/home.html.erb
<div class="page-header">
  <h1>York Street Club </br>
  	<small>
  		A Place for Recovery
    </small>
  </h1>
</div>

</br>

app/views/static_pages/rules.html.erb
<%= provide(:title, "Rules") %>

<div class="container"> 
	<div class="col-lg-9">
			<div class="rules col-lg-offset-3" id="rules">
					<strong>
				
				<h1 id="rules-header">Rules of the Club</h1>
				<span>Any person intoxicated and/or under the influence of drugs will be asked to leave the premises</span></br></br>

				<span>No smoking</span> allowed in the building or on the porch within 18 feet of the front entrance</br>
				<span>No bicycles</span> on the porch or in the building</br>
				<span>No sleeping</span> on the premises</br>
				<span>No panhandling</span></br>
				<span>No dogs</span> allowed on the premises</br>
				<span>No weapons</span> allowed on the premises</br>
				<span>Non Members</span> are welcome 1/2 hour prior and 1/2 hour after scheduled meetings</br>
				<span>Club hours are from 6:30 am to 11:30 pm</span></br>
				</strong>
				
			</div>
	</div>
</div>

app/views/static_pages/schedule.html.erb
<% provide(:title, 'Meetings') %>
<h1>Meetings</h1>
 
<div id='calendar'></div>